### PR TITLE
Using elasticsearch index variable instead of strings, ...

### PR DESCRIPTION
**Pull request by neriberto**
Using elasticsearch index variable instead of strings, creating a variable for doc type.

I did some more changes, trying to use the PEP8

### CODE REVIEW

**Comment by jseidl** [comment]
Great, but you didnt read the PEP8 till the end

"It's okay to say this though:

from subprocess import Popen, PIPE"

So you should not break lines for imports from the same package ;)

The change for the config setting is good though. Can you revert the import changes and submit again please?

**Comment by jseidl** [comment]
Also, this is wrong
+            total = original_document['hits']['total']
+            if 'hits' in original_document and total != 0:

If hits is not in original_document then original_document['hits'] does not exists and the script will fail. Leave as it was. Order matters.

**Comment by jseidl** [comment]
And why did you moved the inline comments? They are perfectly fine and PEP8 is not against https://www.python.org/dev/peps/pep-0008/#inline-comments

**Comment by neriberto** [comment]
all right, I do the change, but the import will pass the 79 characters, ...

I will change only the variables ok ? let's did the change about the PEP8 in another pull request, can be ?

**Comment by jseidl** [comment]
Sure, bring it on (:

Regarding line length, consider:

"Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters."

Also, you can apply the "\" terminator to break the line while maintain the same single line import declaration as this example on PEP8

"with open('/path/to/some/file/you/want/to/read') as file_1, \
     open('/path/to/some/file/being/written', 'w') as file_2:
    file_2.write(file_1.read())"

Thanks for your support!

**Comment by neriberto** [comment]
Good, I had forgotten the line terminator!

**Pull request closed without merging**
